### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e[r].featureReports')

### ISSUE THREAD

**Issue by rufusnufus** [Hydrospheredata/hydroserving-shell-ui#20]
1. I uploaded 1st batch
2. Restarted the plugins
3. Uploaded 2nd and 3rd batch
After that I cannot get overall report for batches
![](https://i.imgur.com/nGODE9W.png)

**Comment by Guzel738** [comment]
What about the data_drift plugin? Does it contain all 3 files?

**Comment by rufusnufus** [comment]
## Drift report screen:
![](https://i.imgur.com/LBf866j.png)

## Profiler screen:
![](https://i.imgur.com/e6wMSVw.png)

**Comment by Guzel738** [comment]
Refreshing the page does not help?

**Comment by rufusnufus** [comment]
No, it doesn't help

**Comment by Guzel738** [comment]
Fix it in #22
